"""Enumerações centrais do protocolo (seção 3 do documento mestre)."""

from __future__ import annotations

from enum import Enum


class RequestType(str, Enum):
    NEW_PRODUCT = "NEW_PRODUCT"
    PRODUCT_CHANGE = "PRODUCT_CHANGE"
    CLIENT_ONBOARDING = "CLIENT_ONBOARDING"
    CLIENT_OFFBOARDING = "CLIENT_OFFBOARDING"
    AI_AGENT_CREATE = "AI_AGENT_CREATE"
    AI_AGENT_UPDATE = "AI_AGENT_UPDATE"
    AI_AGENT_DISABLE = "AI_AGENT_DISABLE"
    DATA_PROCESSING = "DATA_PROCESSING"
    SECURITY_CHANGE = "SECURITY_CHANGE"
    INFRASTRUCTURE_CHANGE = "INFRASTRUCTURE_CHANGE"
    API_INTEGRATION = "API_INTEGRATION"
    VENDOR_ONBOARDING = "VENDOR_ONBOARDING"
    INCIDENT_REPORT = "INCIDENT_REPORT"
    FINANCIAL_OPERATION = "FINANCIAL_OPERATION"
    LEGAL_CONTRACT = "LEGAL_CONTRACT"
    SUPPORT_TICKET = "SUPPORT_TICKET"
    INTERNAL_PROCESS = "INTERNAL_PROCESS"
    AUDIT_ACTION = "AUDIT_ACTION"
    GENERAL_DEMAND = "GENERAL_DEMAND"


class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ApprovalStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    BLOCKED = "BLOCKED"


class ExecutionStatus(str, Enum):
    CREATED = "CREATED"
    TRIAGED = "TRIAGED"
    RISK_CLASSIFIED = "RISK_CLASSIFIED"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    APPROVED = "APPROVED"
    IN_EXECUTION = "IN_EXECUTION"
    IN_TEST = "IN_TEST"
    READY_FOR_RELEASE = "READY_FOR_RELEASE"
    RELEASED = "RELEASED"
    MONITORING = "MONITORING"
    MAINTENANCE = "MAINTENANCE"
    CLOSED = "CLOSED"
    REJECTED = "REJECTED"
    BLOCKED = "BLOCKED"


class DataClassification(str, Enum):
    PUBLIC = "PUBLIC"
    INTERNAL = "INTERNAL"
    CONFIDENTIAL = "CONFIDENTIAL"
    SENSITIVE = "SENSITIVE"
    CRITICAL = "CRITICAL"


class AIAutonomyLevel(str, Enum):
    LEVEL_0_SUGGESTION_ONLY = "LEVEL_0_SUGGESTION_ONLY"
    LEVEL_1_DIAGNOSIS_ONLY = "LEVEL_1_DIAGNOSIS_ONLY"
    LEVEL_2_RECOMMENDATION = "LEVEL_2_RECOMMENDATION"
    LEVEL_3_INTERNAL_ACTION_WITH_APPROVAL = "LEVEL_3_INTERNAL_ACTION_WITH_APPROVAL"
    LEVEL_4_EXTERNAL_ACTION_WITH_APPROVAL = "LEVEL_4_EXTERNAL_ACTION_WITH_APPROVAL"
    LEVEL_5_CRITICAL_AUTONOMOUS_ACTION = "LEVEL_5_CRITICAL_AUTONOMOUS_ACTION"


class IncidentSeverity(str, Enum):
    SEV_4_LOW = "SEV_4_LOW"
    SEV_3_MEDIUM = "SEV_3_MEDIUM"
    SEV_2_HIGH = "SEV_2_HIGH"
    SEV_1_CRITICAL = "SEV_1_CRITICAL"


class IncidentStatus(str, Enum):
    OPEN = "OPEN"
    CONTAINED = "CONTAINED"
    CLOSED = "CLOSED"


class Role(str, Enum):
    """Papéis de aprovação (ver matriz de alçadas)."""

    OWNER = "OWNER"
    AI_OFFICER = "AI_OFFICER"
    DPO = "DPO"
    CTO = "CTO"
    CISO = "CISO"
    LEGAL = "LEGAL"
    CFO = "CFO"
    CEO = "CEO"
    FOUNDER_BOARD = "FOUNDER_BOARD"
